name: 🗂️ Epic
description: Outline a large body of work or project that is broken down into smaller tasks.
type: "Epic"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for outlining this Epic! Please provide comprehensive details of the proposed work.
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: A clear and concise description of the problem this Epic addresses.
      placeholder: The main issue is [...]
    validations:
      required: true
  - type: textarea
    id: additional-resources
    attributes:
      label: Additional Resources
      description: Include links to related documentation, files, or tools needed to complete the task.
    validations:
      required: false
